esphome:
  name: sdm630
  platform: ESP8266
  #board: nodemcuv2
  board: d1_mini
  includes:
    - sdm/SDM_Config_User.h
    - sdm/SDM.h
    - sdm/sdm_esphome.h

wifi:
  ssid: "addssid"
  password: "addpassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sdm630 Fallback Hotspot"
    password: "asspassword"

captive_portal:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
  # level: VERY_VERBOSE
  esp8266_store_log_strings_in_flash: False    

# Enable Home Assistant API
api:
  password: "addpassword"

ota:
  password: "addpassword"

web_server:
  port: 80

time:
  # https://esphome.io/components/time.html
  - platform: homeassistant
    id: hass_time
    timezone: Europe/Berlin  
    
status_led:
  pin:
    number: GPIO0
    inverted: yes    

binary_sensor:
  # https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "SDM630 Status"

switch:
  # https://esphome.io/components/switch/restart.html
  - platform: restart
    name: "SDM630 Restart"
    icon: "mdi:restart-alert"    

mqtt:
  broker: 'IP'
  username: 'user'
  password: 'pass'
  birth_message:
  will_message:
  discovery: true
  discovery_retain: false  
  
i2c:
  sda: D2
  scl: D1  
  scan: True 



  
uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1

sensor:
- platform: uptime
  name: "SDM630 Uptime Sensor"  


- platform: custom
  lambda: |-
    auto sdm_sensors = new SDMComponent();
    App.register_component(sdm_sensors);
    return {sdm_sensors->voltage_sensor, sdm_sensors->current_sensor, sdm_sensors->power_sensor, sdm_sensors->energy_import_sensor,sdm_sensors->power_factor_total_sensor, sdm_sensors->voltage_sensor_1,sdm_sensors->voltage_sensor_2};
  sensors:
    - name: "Voltage Phase 1"
      unit_of_measurement: V
      accuracy_decimals: 1
    - name: "Current"
      unit_of_measurement: A
      accuracy_decimals: 2
    - name: "Power"
      unit_of_measurement: W
      accuracy_decimals: 1
    - name: "Energy import"
      unit_of_measurement: kWh
      accuracy_decimals: 3
    - name: "Power Factor"
      accuracy_decimals: 2
      icon: "mdi:gauge"
    - name: "Voltage Phase 2"
      unit_of_measurement: V
      accuracy_decimals: 1 
    - name: "Voltage Phase 3"
      unit_of_measurement: V
      accuracy_decimals: 1 
- platform: bme280     
  address: 0x76
  temperature:
    name: "SDM630 Temperature"
    oversampling: 16x
  pressure:
    name: "SDM630 Pressure"
  humidity:
    name: "SDM630 Humidity"
  update_interval: 30s
#wifi signal
- platform: wifi_signal
  name: "SDM630 WiFi Signal"
